name: '[CI] On Push to master'

on:
  push:
    branches:
      - master

jobs:
  create_tag:
    name: Bump version and create tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Setup git
        run: |
          git config --global user.email "sushant.kum96@gmail.com"
          git config --global user.name "Sushant Kumar"
      - name: Install npm dependencies
        run: npm install
      - name: Bump version and create tag
        run: npm run release
      - name: Push commit and tag
        run: git push "https://${GITHUB_ACTOR}:${PAT}@github.com/${GITHUB_REPOSITORY}.git" --follow-tags origin master
        env:
          PAT: ${{ secrets.PAT }}
